# Site settings
title: Erin Woo
email: erinpwoo@ucsb.edu
url: https://erinpwoo.github.io
description: "Undergraduate computing student at the University of California, Santa Barbara. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Erin Woo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/erin-woo/
  - title: github
    url: https://github.com/erinpwoo
  - title: facebook
    url: https://www.facebook.com/erin.woo.7/

# Build settings
markdown: kramdown
permalink: pretty
